/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/minecraft-versions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets all available Minecraft versions */
        get: operations["getMinecraftVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/minecraft-versions/version/{versionId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the details for a specific Minecraft version */
        get: operations["getMinecraftVersionDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/minecraft-versions/version/{versionId}/version-manifest/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the Vanilla Launcher version manifest for this version. */
        get: operations["getMinecraftVersionManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/neoforge-versions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets all available NeoForge versions */
        get: operations["getNeoForgeVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/neoforge-versions/version/{versionId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the details for a specific NeoForge version */
        get: operations["getNeoForgeVersionDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/neoforge-versions/version/{versionId}/launcher-manifest/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the Vanilla Launcher version manifest for this NeoForge version. */
        get: operations["getNeoForgeVersionLauncherManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/neoforge-versions/version/{versionId}/installer-profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the profile used by the legacy installer for this NeoForge version. */
        get: operations["getNeoForgeVersionInstallerProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/neoforge-versions/version/{versionId}/server-args-windows/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the command line arguments for launching the server on Windows */
        get: operations["getNeoForgeServerArgsWindows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/neoforge-versions/version/{versionId}/server-args-unix/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the command line arguments for launching the server on Linux/Mac */
        get: operations["getNeoForgeServerArgsUnix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Summarizes an available Minecraft version */
        MinecraftVersionSummary: {
            version: string;
            /** @description The type of this version. Known types include `release` for normal releases, `snapshot` for previews and `experimental` for experimental releases, but may include more types in the future. */
            type: string;
            /**
             * Format: date-time
             * @description The timestamp when this version was released.
             */
            released: string;
            /**
             * Format: date-time
             * @description The timestamp when information about this version was last modified by the meta api.
             */
            last_modified: string;
            /** @description The latest available version of NeoForge for this Minecraft version. This property being non-null indicates that NeoForge has at least one version for this Minecraft version. */
            latest_neoforge_version: string | null;
        } & {
            [key: string]: unknown;
        };
        /** @description Details about a specific Minecraft version */
        MinecraftVersionDetails: {
            version: string;
            /** @description The type of this version. Known types include `release` for normal releases, `snapshot` for previews and `experimental` for experimental releases, but may include more types in the future. */
            type: string;
            /**
             * Format: date-time
             * @description The timestamp when this version was released.
             */
            released: string;
            /**
             * Format: date-time
             * @description The timestamp when information about this version was last modified by the meta api.
             */
            last_modified: string;
            /** @description The major Java version required to run this Minecraft version. */
            javaVersion: number;
        } & {
            [key: string]: unknown;
        };
        /** @description Summarizes an available NeoForge version */
        NeoForgeVersionSummary: {
            version: string;
            /**
             * Format: date-time
             * @description The timestamp when this version was released.
             */
            released: string;
            /**
             * Format: date-time
             * @description The timestamp when information about this version was last modified by the meta api.
             */
            last_modified: string;
            /** @description The Minecraft version this NeoForge version is compatible with. */
            minecraft_version: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Details about a specific NeoForge version */
        NeoForgeVersionDetails: components["schemas"]["SoftwareComponentVersionDetails"] & ({
            /** @description The Minecraft version this NeoForge version is compatible with. */
            minecraft_version: string;
        } & {
            [key: string]: unknown;
        });
        /** @description Details about a specific version of a software component (which is identified by group and artifact id) */
        SoftwareComponentVersionDetails: {
            group_id: string;
            artifact_id: string;
            version: string;
            /**
             * Format: date-time
             * @description The timestamp when this version was released.
             */
            released: string;
            /**
             * Format: date-time
             * @description The timestamp when information about this version was last modified by the meta api.
             */
            last_modified: string;
            /** @description The artifacts available for this component version */
            artifacts: components["schemas"]["SoftwareComponentArtifact"][];
            /** @description Describes the changes released in this version */
            release_notes: components["schemas"]["ReleaseNotes"] | null;
        } & {
            [key: string]: unknown;
        };
        /** @description A single artifact that belongs to a software component version. Artifacts are unique identified within a version by their classifier and extension. */
        SoftwareComponentArtifact: {
            classifier: string | null;
            /** @description A null extension indicates the file has no file extension, not the usual Maven default of 'jar'. */
            extension: string | null;
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            last_modified: string;
            url: string;
            md5_checksum: string;
            sha1_checksum: string;
            sha256_checksum: string;
            sha512_checksum: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Release notes for a software version */
        ReleaseNotes: {
            text: string;
            markdown: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Webhook payload that contains all occurred events in a list form. */
        EventsPayload: {
            events: components["schemas"]["EventPayload"][];
        } & {
            [key: string]: unknown;
        };
        /** @description Webhook payload containing a single event. */
        EventPayload: {
            type: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created: string;
        };
        SoftwareComponentVersionEventPayload: {
            group_id: string;
            artifact_id: string;
            version: string;
        };
        NewSoftwareComponentVersionEventPayload: components["schemas"]["SoftwareComponentVersionEventPayload"] & Omit<components["schemas"]["EventPayload"], "type">;
        ModifiedSoftwareComponentVersionEventPayload: components["schemas"]["SoftwareComponentVersionEventPayload"] & Omit<components["schemas"]["EventPayload"], "type">;
        RemovedSoftwareComponentVersionEventPayload: components["schemas"]["SoftwareComponentVersionEventPayload"] & Omit<components["schemas"]["EventPayload"], "type">;
        /** @description Webhook payload that gives a condensed description of changes to multiple software components. */
        SoftwareComponentsChangesPayload: {
            components: components["schemas"]["SoftwareComponentChangesPayload"][];
        } & {
            [key: string]: unknown;
        };
        /** @description Webhook payload that gives a condensed description of changes to a single software component. */
        SoftwareComponentChangesPayload: {
            group_id: string;
            artifact_id: string;
            new_versions: string[];
            modified_versions: string[];
            removed_versions: string[];
        } & {
            [key: string]: unknown;
        };
        /** @description Webhook payload that gives a condensed description of new, modified or removed NeoForge versions. */
        NeoForgeVersionChangesPayload: {
            new_versions: string[];
            modified_versions: string[];
            removed_versions: string[];
        } & {
            [key: string]: unknown;
        };
        /** @description Webhook payload that gives a condensed description of new, modified or removed Minecraft versions. */
        MinecraftVersionChangesPayload: {
            new_versions: string[];
            modified_versions: string[];
            removed_versions: string[];
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMinecraftVersions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list of available Minecraft versions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinecraftVersionSummary"][];
                };
            };
        };
    };
    getMinecraftVersionDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Details about a specific Minecraft version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinecraftVersionDetails"];
                };
            };
        };
    };
    getMinecraftVersionManifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Vanilla Launcher version manifest for this version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description The URL where the Vanilla Launcher version manifest is located. */
            307: {
                headers: {
                    Location?: {
                        "text/plain": "http://dummy";
                    };
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getNeoForgeVersions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list of available NeoForge versions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeoForgeVersionSummary"][];
                };
            };
        };
    };
    getNeoForgeVersionDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Details about a specific NeoForge version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeoForgeVersionDetails"];
                };
            };
        };
    };
    getNeoForgeVersionLauncherManifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Vanilla Launcher version manifest for this version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    getNeoForgeVersionInstallerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The legacy installer profile for this version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    getNeoForgeServerArgsWindows: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The command line arguments for launching the server on Windows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getNeoForgeServerArgsUnix: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The command line arguments for launching the server on Linux/Mac */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
